# Generated by Django 5.2.17 on 2026-09-17 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0002_freelancetask_freelancetaskupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEscalationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('reminder_offsets', models.CharField(default='3,1,0', max_length=255)),
                ('remind_freelancer', models.BooleanField(default=True)),
                ('remind_pic', models.BooleanField(default=True)),
                ('escalation_cc_emails', models.CharField(blank=True, max_length=1024)),
                ('escalate_after_days', models.PositiveSmallIntegerField(default=1)),
                ('max_escalations', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_task_escalation_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task escalation policy',
                'verbose_name_plural': 'Task escalation policies',
            },
        ),
        migrations.CreateModel(
            name='TaskReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('REMINDER', 'Reminder'), ('ESCALATION', 'Escalation')], max_length=12)),
                ('offset_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recipient_emails', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='freelance.freelancetask')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
