# Generated by Django 5.2.17 on 2026-09-17 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LEAVE_SUBMITTED', 'Izin/Cuti - Pengajuan Baru'), ('LEAVE_APPROVED', 'Izin/Cuti - Disetujui'), ('LEAVE_REJECTED', 'Izin/Cuti - Ditolak'), ('CONTRACT', 'End of Contract'), ('BIRTHDAY', 'Birthday')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=512)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-app')], max_length=16)),
                ('event', models.CharField(choices=[('LEAVE_SUBMITTED', 'Izin/Cuti - Pengajuan Baru'), ('LEAVE_APPROVED', 'Izin/Cuti - Disetujui'), ('LEAVE_REJECTED', 'Izin/Cuti - Ditolak'), ('CONTRACT', 'End of Contract'), ('BIRTHDAY', 'Birthday')], max_length=32)),
                ('recipient_email', models.CharField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='SENT', max_length=16)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_hr_emails', models.CharField(default='hrgaferaco@gmail.com', max_length=1024)),
                ('birthday_h1_enabled', models.BooleanField(default=True)),
                ('birthday_h0_enabled', models.BooleanField(default=True)),
                ('contract_offsets', models.CharField(default='30,14,7,3,1,0', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_hr_users', models.ManyToManyField(blank=True, related_name='notification_hr_recipient_of', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification setting',
                'verbose_name_plural': 'Notification settings',
            },
        ),
    ]
