# Generated by Django 5.2.17 on 2026-10-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('LEAVE_SUBMITTED', 'Izin/Cuti - Pengajuan Baru'), ('LEAVE_APPROVED', 'Izin/Cuti - Disetujui'), ('LEAVE_REJECTED', 'Izin/Cuti - Ditolak'), ('REIMBURSEMENT_SUBMITTED', 'Reimbursement - Pengajuan Baru'), ('CONTRACT', 'End of Contract'), ('BIRTHDAY', 'Birthday')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationdeliverylog',
            name='event',
            field=models.CharField(choices=[('LEAVE_SUBMITTED', 'Izin/Cuti - Pengajuan Baru'), ('LEAVE_APPROVED', 'Izin/Cuti - Disetujui'), ('LEAVE_REJECTED', 'Izin/Cuti - Ditolak'), ('REIMBURSEMENT_SUBMITTED', 'Reimbursement - Pengajuan Baru'), ('CONTRACT', 'End of Contract'), ('BIRTHDAY', 'Birthday')], max_length=32),
        ),
    ]
