# Generated by Django 5.2.17 on 2026-09-02 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0011_backfill_company_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('category', models.CharField(choices=[('EARNING_FIXED', 'Earning Fixed'), ('EARNING_VARIABLE', 'Earning Variable'), ('DEDUCTION', 'Deduction')], default='EARNING_FIXED', max_length=32)),
                ('calculation_type', models.CharField(choices=[('FIXED_AMOUNT', 'Fixed Amount'), ('VARIABLE', 'Variable'), ('PERCENTAGE', 'Percentage')], default='FIXED_AMOUNT', max_length=32)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_reimbursement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Component',
                'verbose_name_plural': 'Payroll Components',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('components', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='personnel.employee')),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
                'ordering': ['-effective_from'],
            },
        ),
    ]
