# Generated by Django 5.2.17 on 2026-09-02 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('personnel', '0011_backfill_company_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_fixed_earning', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_variable_earning', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reimbursement_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='personnel.employee')),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
                'ordering': ['employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=128)),
                ('component_code', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('EARNING_FIXED', 'Earning Fixed'), ('EARNING_VARIABLE', 'Earning Variable'), ('DEDUCTION', 'Deduction')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source', models.CharField(choices=[('SYSTEM', 'System'), ('MANUAL', 'Manual')], default='SYSTEM', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payroll')),
                ('payroll_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_items', to='payroll.payrollcomponent')),
            ],
            options={
                'verbose_name': 'Payroll Item',
                'verbose_name_plural': 'Payroll Items',
                'ordering': ['payroll', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveIntegerField()),
                ('period_year', models.PositiveIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('LOCKED', 'Locked')], default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('period_month', 'period_year')},
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.payrollperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('period', 'employee')},
        ),
    ]
