# Generated by Django 5.2.17 on 2026-09-10 01:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payroll_payrollitem_payrollperiod_payroll_period_and_more'),
        ('personnel', '0014_position_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('dtp_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000000'), help_text='THP di bawah/sama dengan nilai ini → PPh DTP (tidak dipotong riil).', max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Config',
                'verbose_name_plural': 'Tax Configs',
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='is_dtp',
            field=models.BooleanField(default=False, help_text='True = PPh DTP: tercetak di slip tapi tidak dikurangi dari transfer.'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pro_rata_factor',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=9),
        ),
        migrations.AddField(
            model_name='payroll',
            name='ptkp_status_snapshot',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='payroll',
            name='ter_category_snapshot',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='payroll',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payroll',
            name='unpaid_leave_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollcomponent',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmployeeTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptkp_status', models.CharField(default='TK/0', max_length=4)),
                ('tax_scheme', models.CharField(choices=[('NORMAL', 'Normal'), ('GROSS_UP', 'Gross Up')], default='NORMAL', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='personnel.employee')),
            ],
            options={
                'verbose_name': 'Employee Tax Profile',
                'verbose_name_plural': 'Employee Tax Profiles',
            },
        ),
        migrations.CreateModel(
            name='TerBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ter_category', models.CharField(choices=[('A', 'TER A'), ('B', 'TER B'), ('C', 'TER C')], max_length=1)),
                ('bruto_lower', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bruto_upper', models.DecimalField(blank=True, decimal_places=2, help_text='NULL = tanpa batas atas (bracket tertinggi).', max_digits=14, null=True)),
                ('rate_pct', models.DecimalField(decimal_places=4, help_text='Persen tarif TER, mis. 0.2500 = 0,25%.', max_digits=6)),
                ('tax_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ter_brackets', to='payroll.taxconfig')),
            ],
            options={
                'verbose_name': 'TER Bracket',
                'verbose_name_plural': 'TER Brackets',
                'ordering': ['ter_category', 'bruto_lower'],
            },
        ),
    ]
