# Generated by Django 5.2.17 on 2026-09-10 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_taxconfig_payroll_is_dtp_payroll_pro_rata_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='pph_annual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pph_prior_months',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='taxconfig',
            name='annual_layer_limits',
            field=models.JSONField(blank=True, default=list, help_text='Batas atas lapisan PKP tahunan (Pasal 17), mis. [60000000, 250000000, 500000000, 5000000000]. Kosong = default 60jt/250jt/500jt/5M. Tarif lapisan 5/15/25/30% tetap (statis, PMK 168/2023).'),
        ),
        migrations.CreateModel(
            name='AnnualTaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_order', models.PositiveSmallIntegerField(help_text='Urutan lapisan PKP tahunan (1 = terendah, 5 = tertinggi).')),
                ('pkp_lower', models.DecimalField(decimal_places=2, help_text='Batas bawah lapisan (indeks biaya 0).', max_digits=16)),
                ('pkp_upper', models.DecimalField(blank=True, decimal_places=2, help_text='Batas atas lapisan; NULL = tanpa batas (lapisan tertinggi).', max_digits=16, null=True)),
                ('rate_pct', models.DecimalField(decimal_places=4, help_text='Persen tarif Pasal 17, mis. 5 = 5%.', max_digits=6)),
                ('tax_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_brackets', to='payroll.taxconfig')),
            ],
            options={
                'verbose_name': 'Annual Tax Bracket',
                'verbose_name_plural': 'Annual Tax Brackets',
                'ordering': ['tax_config', 'layer_order'],
                'constraints': [models.UniqueConstraint(fields=('tax_config', 'layer_order'), name='uniq_annual_bracket_per_layer')],
            },
        ),
    ]
