# Generated by Django 5.2.17 on 2026-09-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_pph_annual_payroll_pph_prior_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PT Feraco', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('department_name', models.CharField(default='HRGA DEPARTMENT', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Config',
                'verbose_name_plural': 'Company Config',
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='slip_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
