# Generated by Django 5.2.17 on 2026-09-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_companyconfig_payroll_slip_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconfig',
            name='address',
            field=models.TextField(default='PURI SENTRA NIAGA, JL. RAYA KALIMALANG B-42, RT.1/RW.7\nJAKARTA TIMUR - DKI JAKARTA 13620'),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='name',
            field=models.CharField(default='PT FERY AGUNG CORINDOTAMA', max_length=255),
        ),
    ]
