# Generated by Django 5.2.17 on 2026-09-25 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_role_key'),
        ('kms', '0001_initial'),
        ('personnel', '0016_employeecontract_pkwt_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='visibility',
            field=models.CharField(choices=[('ALL', 'Semua Karyawan'), ('ROLE', 'Role Tertentu'), ('DEPARTMENT', 'Departemen Tertentu'), ('USER', 'User Tertentu'), ('PRIVATE', 'Private')], default='ALL', max_length=12),
        ),
        migrations.CreateModel(
            name='KnowledgeArticleDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='kms.knowledgearticle')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kms_article_links', to='personnel.department')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='department_targets',
            field=models.ManyToManyField(blank=True, related_name='kms_articles_targeted', through='kms.KnowledgeArticleDepartment', to='personnel.department'),
        ),
        migrations.CreateModel(
            name='KnowledgeArticleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='kms.knowledgearticle')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kms_article_links', to='accounts.role')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='role_targets',
            field=models.ManyToManyField(blank=True, related_name='kms_articles_targeted', through='kms.KnowledgeArticleRole', to='accounts.role'),
        ),
        migrations.CreateModel(
            name='KnowledgeArticleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='kms.knowledgearticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kms_article_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='user_targets',
            field=models.ManyToManyField(blank=True, related_name='kms_articles_targeted', through='kms.KnowledgeArticleUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='knowledgearticledepartment',
            constraint=models.UniqueConstraint(fields=('article', 'department'), name='kms_article_department_unique'),
        ),
        migrations.AddConstraint(
            model_name='knowledgearticlerole',
            constraint=models.UniqueConstraint(fields=('article', 'role'), name='kms_article_role_unique'),
        ),
        migrations.AddConstraint(
            model_name='knowledgearticleuser',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='kms_article_user_unique'),
        ),
    ]
