# Generated by Django 5.2.17 on 2026-08-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_position_parent_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='parent_position',
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='probation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='probation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('RENEWED', 'Renewed')], default='DRAFT', max_length=16),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='contract_type',
            field=models.CharField(choices=[('PKWT', 'PKWT'), ('PKWTT', 'PKWTT')], max_length=16),
        ),
    ]
