# Generated by Django 5.2.17 on 2026-08-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_remove_position_parent_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='termination_reason',
            field=models.TextField(blank=True),
        ),
    ]
