# Generated by Django 5.2.17 on 2026-08-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_employeecontract_termination_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
