# Generated by Django 5.2.17 on 2026-08-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_employeecontract_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='parent_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='personnel.position'),
        ),
    ]
