# Generated by Django 5.2.17 on 2026-08-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_position_parent_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
