# Generated by Django 5.2.17 on 2026-08-31 03:34

from django.db import migrations
from django.db.models import F


def backfill(apps, schema_editor):
    Personnel = apps.get_model('personnel', 'Personnel')
    Personnel.objects.filter(company_email='').update(company_email=F('personal_email'))


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_personnel_company_email'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
