# Generated by Django 5.2.17 on 2026-09-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_backfill_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Laki-laki'), ('FEMALE', 'Perempuan')], max_length=8),
        ),
        migrations.AddField(
            model_name='personnel',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Belum Menikah'), ('MARRIED', 'Menikah'), ('DIVORCED', 'Cerai'), ('WIDOWED', 'Janda/Duda')], max_length=16),
        ),
        migrations.AddField(
            model_name='personnel',
            name='placement',
            field=models.CharField(blank=True, choices=[('JAKARTA', 'Jakarta'), ('JOGJA', 'Jogja')], max_length=16),
        ),
        migrations.AddField(
            model_name='personnel',
            name='religion',
            field=models.CharField(blank=True, choices=[('ISLAM', 'Islam'), ('PROTESTAN', 'Protestan'), ('KATOLIK', 'Katolik'), ('HINDU', 'Hindu'), ('BUDDHA', 'Buddha'), ('KONGHUCU', 'Konghucu')], max_length=16),
        ),
    ]
