# Generated by Django 5.2.17 on 2026-09-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_personnel_gender_personnel_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
