# Generated by Django 5.2.17 on 2026-09-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_personnel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGEMENT', 'Management')], default='EMPLOYEE', max_length=16),
        ),
    ]
