# Generated by Django 5.2.17 on 2026-09-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_position_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelancer',
            options={'ordering': ['full_name']},
        ),
        migrations.AddField(
            model_name='freelancer',
            name='blacklist_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='domicile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='rate_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='rate_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('PER_DAY', 'Per Hari'), ('PER_EVENT', 'Per Event')], max_length=16),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
