# Generated by Django 5.2.17 on 2026-09-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0015_alter_freelancer_options_freelancer_blacklist_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='pkwt_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
