# Generated by Django 5.2.17 on 2026-09-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_revoke_supabase_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inactive_by_employee',
            field=models.BooleanField(default=False),
        ),
    ]
