# Generated by Django 5.2.17 on 2026-09-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_inactive_by_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='key',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR_STAFF', 'HR Staff'), ('HR_LEAD', 'HR Lead'), ('EMPLOYEE', 'Employee'), ('MANAGEMENT', 'Management'), ('GENERAL_MANAGER', 'General Manager')], max_length=32, unique=True),
        ),
    ]
