# Generated by Django 5.2.17 on 2026-08-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_job_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied')], default='APPLIED', max_length=32),
        ),
    ]
