# Generated by Django 5.2.17 on 2026-09-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_alter_candidate_status_candidatestatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruitment_type',
            field=models.CharField(choices=[('INHOUSE', 'Inhouse'), ('FREELANCE', 'Freelance')], default='INHOUSE', max_length=16),
        ),
    ]
