# Generated by Django 5.2.17 on 2026-10-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0003_taskescalationpolicy_taskreminderlog'),
        ('recruitment', '0008_freelanceapplyform_candidateskill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='freelance.skill'),
        ),
    ]
