# Generated by Django 5.2.17 on 2026-09-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='use_end_date',
            field=models.BooleanField(default=False),
        ),
    ]
