# Generated by Django 5.2.17 on 2026-09-03 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('personnel', '0011_backfill_company_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nik', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('birth_place', models.CharField(blank=True, max_length=128)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('bank_account_number', models.CharField(blank=True, max_length=64)),
                ('bank_account_name', models.CharField(blank=True, max_length=255)),
                ('npwp', models.CharField(blank=True, max_length=32)),
                ('bpjs_kesehatan', models.CharField(blank=True, max_length=32)),
                ('bpjs_ketenagakerjaan', models.CharField(blank=True, max_length=32)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('PKWT', 'PKWT'), ('PKWTT', 'PKWTT')], default='PKWTT', max_length=16)),
                ('probation_enabled', models.BooleanField(default=False)),
                ('probation_start_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_data', to='personnel.department')),
                ('onboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='onboarding.onboarding')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_data', to='personnel.position')),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_reports', to='personnel.personnel')),
            ],
            options={
                'verbose_name_plural': 'onboarding data',
            },
        ),
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('KTP', 'KTP'), ('KK', 'Kartu Keluarga'), ('NPWP', 'NPWP'), ('BPJS_KESEHATAN', 'BPJS Kesehatan'), ('BPJS_KETENAGAKERJAAN', 'BPJS Ketenagakerjaan'), ('BUKU_REKENING', 'Buku Rekening'), ('IJAZAH', 'Ijazah'), ('KONTRAK_KERJA', 'Kontrak Kerja'), ('LAINNYA', 'Lainnya')], default='LAINNYA', max_length=32)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=512)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.onboarding')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboarding_docs', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_onboarding_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('required', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='onboarding.onboarding')),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'unique_together': {('onboarding', 'code')},
            },
        ),
    ]
