# Generated by Django 5.2.17 on 2026-09-03 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_onboardingdata_onboardingdocument_and_more'),
        ('personnel', '0011_backfill_company_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboardings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_entry', to='personnel.employee'),
        ),
    ]
