# Generated by Django 5.2.17 on 2026-09-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_onboarding_completed_by_onboarding_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingdocument',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
