# Generated by Django 5.2.17 on 2026-08-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='balance_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
