# Generated by Django 5.2.17 on 2026-09-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest_balance_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='kind',
            field=models.CharField(choices=[('LEAVE', 'Cuti'), ('PERMISSION', 'Izin')], default='LEAVE', max_length=16),
        ),
    ]
