# Generated by Django 5.2.17 on 2026-09-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leavetype_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='deducts_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leaves.leavetype'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_days_per_request',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_days_without_attachment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='min_tenure_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
