# Generated by Django 5.2.17 on 2026-10-01 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leavetype_carry_forward_max_leavetype_deducts_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequestDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='leaves.leaverequest')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('leave_request', 'date')},
            },
        ),
    ]
