# Generated by Django 5.2.17 on 2026-10-05 09:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_deactivate_unpaid_leave_type'),
        ('personnel', '0016_employeecontract_pkwt_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='adjustment_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='leaverequestdate',
            name='portion',
            field=models.CharField(choices=[('FULL', 'Full Day'), ('HALF', 'Half Day')], default='FULL', max_length=4),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='allocated_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='remaining_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6),
        ),
        migrations.CreateModel(
            name='LeaveQuotaAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=1, max_digits=6)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_quota_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_quota_adjustments', to='personnel.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_adjustments', to='leaves.leavetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
