# Generated by Django 5.2.17 on 2026-09-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0002_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='project_category',
            field=models.CharField(blank=True, choices=[('OPERASIONAL_FERACO_JAKARTA', 'Operasional Feraco Jakarta'), ('OPERASIONAL_FERACO_JOGJA', 'Operasional Feraco Jogja'), ('GPFE', 'GPFE'), ('INACRAFT', 'Inacraft'), ('PENAS', 'Penas'), ('LEARNING_DEVELOPMENT', 'Learning & Development'), ('OTHER', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='project_category_other',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
